// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID          int32
	Title       string
	PublishDate pgtype.Timestamptz
	Description pgtype.Text
	ImgUrl      pgtype.Text
	Categories  pgtype.Text
	Url         string
	Website     string
	CreatedAt   pgtype.Timestamptz
}
