// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: posts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT  INTO posts
    (title , publish_date , description , img_url , categories , url , website )
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, publish_date, description, img_url, categories, url, website, created_at
`

type CreatePostParams struct {
	Title       string
	PublishDate pgtype.Timestamptz
	Description pgtype.Text
	ImgUrl      pgtype.Text
	Categories  pgtype.Text
	Url         string
	Website     string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Title,
		arg.PublishDate,
		arg.Description,
		arg.ImgUrl,
		arg.Categories,
		arg.Url,
		arg.Website,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.PublishDate,
		&i.Description,
		&i.ImgUrl,
		&i.Categories,
		&i.Url,
		&i.Website,
		&i.CreatedAt,
	)
	return i, err
}
